### PR TITLE
Added HTML AST parser support

### PR DESCRIPTION
**Pull request by marcelaraujo**
:)

@stephanebachelier

### CODE REVIEW

**Comment by stephanebachelier** [comment]
@marcelaraujo I hope this is your last PR :) 
Need to fix a failing test

**Comment by marcelaraujo** [comment]
Sorry man.

I did wrong merge after rebase. Not it's ok.

:+1:

**Comment by stephanebachelier** [comment]
No problem!
:+1: @marcelaraujo

**Comment by marcelaraujo** [comment]
Do you will change the version?

**Comment by XhmikosR** [comment]
Always squash useless patches...

**Comment by stephanebachelier** [comment]
@XhmikosR you're right. 
Having this PR merged was already complicated. Appveyor being really slow, and jscs having issue with esparse link.
So yes I've missed this final useless patch. But IMO it's not really an issue compared to the work being done, and being merge into `dev` we can still squash this patch.

**Comment by stephanebachelier** [comment]
@XhmikosR I've updated all the commit messages and squash this useless patch. But for now it's only in  another branch:
https://github.com/stephanebachelier/grunt-usemin/commits/dev-rebased

This branch is missing the merge commits which might be an issue for you.

**Comment by stephanebachelier** [comment]
@marcelaraujo before updating the version we need some actions. 
I'll create an issue, kind of roadmap, with issues to fix and actions needed to be able to release a new version.

For now you can use the #dev branch. In npm you can use `grunt-usemin#dev`.

**Comment by marcelaraujo** [comment]
Ok guys

I will help with anything :)

**Comment by XhmikosR** [comment]
Looks better now. Although, the merge commits are gone. There must be a way to keep those, but I've never tried that.

**Pull request merged**
