### PR TITLE
Remove peerDeps

### PR DESCRIPTION
**Pull request by vladikoff**
Ref https://github.com/gruntjs/grunt/issues/1116

### CODE REVIEW

**Comment by sindresorhus** [comment]
`peerDependencies` no longer install anything in npm@3, but they're still useful to indicate what peer version they're compatible with.

**Comment by vladikoff** [comment]
@sindresorhus yeap, but it will block install of the plugin on npm@2 once we release Grunt 1.0

cc @shama

**Comment by sindresorhus** [comment]
How so? The version range is *anything* above 0.4.0.

**Comment by vladikoff** [comment]
@sindresorhus ah okay excellent! that would work, thanks!

**Pull request closed without merging**
