### PR TITLE
Update regexp to support spaces in output

### LINKED ISSUE #512: Build pattern regex doesn't support url path with space
My build comment template in my html like this:
```
<!-- build:css <%- staticBase%>/css/index/index.css -->
<link href="<%- staticBase %>/css/common/base.css<%- version %>" type="text/css" rel="stylesheet">
<link href="<%- staticBase %>/css/index/index.css<%- version %>" type="text/css" rel="stylesheet">
<link href="<%- staticBase %>/css/common/itemListTemplate.css<%- version %>" type="text/css" rel="stylesheet">
<!-- endbuild -->

```

the staticBase variable is the DNSUrl i will render by grunt template, the first line `<!-- build:css <%- staticBase%>/css/index/index.css -->` , you can see there is a space before word `staticBase`, but the usemin build pattern can't parse this pattern.

I check the usemin rebuild pattern is `/<!--\s*build:(\w+)(?:\(([^\)]+)\))?\s*([^\s]+)\s*-->/`, it does't support   build path with a space, when i remove the space before `staticBase` word, it works fine.

### PR DESCRIPTION
**Pull request by stephanebachelier**
Fixes #512.

Before merging this issue we need a code review but also it should be good to have @JackZhang1988 come back to us.

### CODE REVIEW

**Comment by stephanebachelier** [comment]
Before merging this issue we need a code review but also it should be good to have @JackZhang1988 come back to us.

**Comment by JackZhang1988** [comment]
sorry for replay so late. i'm on my holiday. I have test this, and it works in my case. thanks a lot!

**Comment by stephanebachelier** [comment]
Thanks @JackZhang1988 for your feedback

**Comment by stephanebachelier** [comment]
We should wait for html parser migration as this PR might not needed.

**Comment by stephanebachelier** [comment]
Closing this issue html parser on `dev` branch and need more explanation in #512

**Pull request closed without merging**
