### PR TITLE
fix(jscs): update rules

### PR DESCRIPTION
**Pull request by stephanebachelier**

### CODE REVIEW

**Comment by arthurvr** [comment]
> Do not merge as I need to update when the grunt preset will be defined for jscs.

@stephanebachelier Any update in here? For me this LGTM as it is.

**Comment by stephanebachelier** [comment]
@arthurvr I need to review my PR as it was done before grunt preset where validated on jscs. Will take some time tomorrow.

**Comment by stephanebachelier** [comment]
@arthurvr rebased on master

CC @sindresorhus

**Comment by arthurvr** [comment]
Looks good to me

**Comment by sindresorhus** [comment]
Thanks @stephanebachelier :)

**Comment by stephanebachelier** [comment]
fix #482

**Pull request merged**
