### PR TITLE
Added HTML parser support

### PR DESCRIPTION
**Pull request by marcelaraujo**
:)

@stephanebachelier It's squashed into one single commit.

Thanks

### CODE REVIEW

**Comment by XhmikosR** [comment]
Why do we need run.js in root? Can't you move it in test/?

**Comment by marcelaraujo** [comment]
Sorry. I forgot remove it. It will be done.

**Comment by marcelaraujo** [comment]
It's done.

Will it be merged?

**Comment by XhmikosR** [comment]
I'll leave this to @stephanebachelier. But you should squash those 2 commits.

**Comment by marcelaraujo** [comment]
Squash again?

:sweat: 

Let's go...

**Comment by marcelaraujo** [comment]
It's done.

**Comment by marcelaraujo** [comment]
Any feedback guys?

I'm using my own repository but I wish move to the right target

:blush:

**Comment by stevemao** [comment]
Any reason you use parse5 instead of cheerio?

**Comment by marcelaraujo** [comment]
Only one reason, performance!

**Comment by stephanebachelier** [comment]
@marcelaraujo sorry for the delay, client work in the pipe. I really want to merge your work as it's a major feature and will solve lots of issues in this repo. I come back to you this week after having made some tests on real projects.

**Comment by stephanebachelier** [comment]
@marcelaraujo @XhmikosR I would like to have the #518 to pass before if it might be accepted, as I had hard time rebasing the work done in #306. This PR should be easy to rebase on #518.

**Comment by marcelaraujo** [comment]
Ok.

:+1:

**Comment by stephanebachelier** [comment]
@marcelaraujo BTW feel free to ping me if I ever get lost in client work :)

**Comment by marcelaraujo** [comment]
I don't think we will have problems between both PR's because we work on different files. Maybe some tests will break... maybe...

:)

**Comment by stephanebachelier** [comment]
@marcelaraujo I've created a `dev` branch to merge majors PR. Could you create another PR on top of `dev` branch. You can't edit a PR.

**Pull request closed without merging**
